import { Restaurant, RestaurantTable, MenuItem, MenuCategory, Order, InventoryItem, AuditLog, AIInsight, UserProfile } from './types';

export const INITIAL_RESTAURANT: Restaurant = {
  id: 'rest-smartserve-01',
  name: 'SmartServe OS Bistro',
  tagline: 'Next-Gen Operational Intelligence & QR Table Service',
  tablesCount: 8,
  currency: '$',
  qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://smartserve.os/table/4',
  address: '742 Culinary Blvd, Tech City',
  phone: '+1 (800) 555-SERVE',
};

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-manager-01',
    email: 'alex.manager@smartserve.os',
    fullName: 'Alex Rivera (Manager)',
    role: 'manager',
    restaurantId: 'rest-smartserve-01',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-kitchen-01',
    email: 'chef.marco@smartserve.os',
    fullName: 'Chef Marco (Head Chef)',
    role: 'kitchen',
    restaurantId: 'rest-smartserve-01',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-staff-01',
    email: 'sarah.floor@smartserve.os',
    fullName: 'Sarah Jenkins (Floor Staff)',
    role: 'staff',
    restaurantId: 'rest-smartserve-01',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'user-customer-01',
    email: 'guest.table4@smartserve.os',
    fullName: 'Table 4 Guest (Diner)',
    role: 'customer',
    restaurantId: 'rest-smartserve-01',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_CATEGORIES: MenuCategory[] = [
  { id: 'cat-1', name: 'starters', label: 'Starters & Appetizers', description: 'Artisanal bites, crisp salads & fresh tapas', displayOrder: 1, isActive: true },
  { id: 'cat-2', name: 'mains', label: 'Chef Signature Mains', description: 'Handcrafted pasta, premium wagyu & fresh seafood', displayOrder: 2, isActive: true },
  { id: 'cat-3', name: 'desserts', label: 'Decadent Desserts', description: 'Warm lava cakes, artisanal gelatos & sweet reductions', displayOrder: 3, isActive: true },
  { id: 'cat-4', name: 'beverages', label: 'Craft Beverages & Cocktails', description: 'Smoked mixology cocktails & specialty matcha coffees', displayOrder: 4, isActive: true },
  { id: 'cat-5', name: 'specials', label: 'Daily Chef Specials', description: 'Seasonal market delicacies limited availability', displayOrder: 5, isActive: true },
];

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: 'item-1',
    name: 'Truffle Tagliatelle',
    description: 'Fresh handmade pasta tossed in black truffle cream, wild mushrooms, and 24-month aged Parmigiano Reggiano.',
    category: 'mains',
    price: 26.50,
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281211?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    prepTimeMinutes: 14,
    isVegan: false,
    isGF: false,
    calories: 680,
    stockCount: 18,
  },
  {
    id: 'item-2',
    name: 'Smoked Wagyu Burger',
    description: 'Double Wagyu beef patty, applewood smoked cheddar, caramelized onions, black garlic aioli on brioche.',
    category: 'mains',
    price: 22.00,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    prepTimeMinutes: 12,
    isSpicy: false,
    calories: 890,
    stockCount: 12,
  },
  {
    id: 'item-3',
    name: 'Pan-Seared Atlantic Salmon',
    description: 'Crispy skin salmon over saffron risotto, asparagus spears, and citrus dill beurre blanc.',
    category: 'mains',
    price: 28.00,
    imageUrl: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    prepTimeMinutes: 16,
    isGF: true,
    calories: 540,
    stockCount: 5,
  },
  {
    id: 'item-4',
    name: 'Artisan Burrata & Heirloom Salad',
    description: 'Creamy Puglia burrata, heirloom tomatoes, fresh basil pesto, balsamic glaze, and grilled sourdough.',
    category: 'starters',
    price: 16.50,
    imageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb12765?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    prepTimeMinutes: 8,
    isVegan: false,
    isGF: false,
    calories: 420,
    stockCount: 22,
  },
  {
    id: 'item-5',
    name: 'Charred Octopus Tapas',
    description: 'Spanish octopus, smoky paprika fingerling potatoes, romesco sauce, and pickled shallots.',
    category: 'starters',
    price: 18.00,
    imageUrl: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    prepTimeMinutes: 10,
    isSpicy: true,
    isGF: true,
    calories: 380,
    stockCount: 14,
  },
  {
    id: 'item-6',
    name: 'Valrhona Chocolate Lava Cake',
    description: 'Warm molten 70% dark chocolate center, madagascar vanilla bean gelato, and raspberry reduction.',
    category: 'desserts',
    price: 12.50,
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    prepTimeMinutes: 10,
    isVegan: false,
    calories: 520,
    stockCount: 15,
  },
  {
    id: 'item-7',
    name: 'Smoked Yuzu Dragon Cocktail',
    description: 'Japanese whiskey, yuzu juice, dragonfruit syrup, mint leaf, and rosemary smoke vapor block.',
    category: 'beverages',
    price: 15.00,
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    prepTimeMinutes: 5,
    isVegan: true,
    isGF: true,
    calories: 190,
    stockCount: 40,
  },
  {
    id: 'item-8',
    name: 'Matcha Espresso Fusion',
    description: 'Ceremonial grade Uji matcha, oat milk, double shot specialty espresso, and vanilla foam.',
    category: 'beverages',
    price: 7.50,
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?auto=format&fit=crop&w=600&q=80',
    isAvailable: true,
    prepTimeMinutes: 4,
    isVegan: true,
    isGF: true,
    calories: 140,
    stockCount: 50,
  },
];

export const INITIAL_TABLES: RestaurantTable[] = [
  { id: 'tbl-1', number: 1, capacity: 2, status: 'occupied', currentOrderId: 'ord-101', waiterCalled: false, guestsCount: 2, assignedStaffName: 'Sarah J.', qrToken: 'tbl_tok_01_a9f2x' },
  { id: 'tbl-2', number: 2, capacity: 4, status: 'occupied', currentOrderId: 'ord-102', waiterCalled: true, waiterCallTime: '2 mins ago', guestsCount: 3, assignedStaffName: 'Sarah J.', qrToken: 'tbl_tok_02_b8k1y' },
  { id: 'tbl-3', number: 3, capacity: 2, status: 'available', waiterCalled: false, qrToken: 'tbl_tok_03_c7m3z' },
  { id: 'tbl-4', number: 4, capacity: 6, status: 'occupied', currentOrderId: 'ord-103', waiterCalled: false, guestsCount: 5, assignedStaffName: 'Sarah J.', qrToken: 'tbl_tok_04_d6p4w' },
  { id: 'tbl-5', number: 5, capacity: 4, status: 'needs_cleaning', waiterCalled: false, qrToken: 'tbl_tok_05_e5r5v' },
  { id: 'tbl-6', number: 6, capacity: 8, status: 'reserved', waiterCalled: false, qrToken: 'tbl_tok_06_f4t6u' },
  { id: 'tbl-7', number: 7, capacity: 2, status: 'available', waiterCalled: false, qrToken: 'tbl_tok_07_g3v7t' },
  { id: 'tbl-8', number: 8, capacity: 4, status: 'available', waiterCalled: false, qrToken: 'tbl_tok_08_h2x8s' },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    tableNumber: 1,
    tableToken: 'tbl_tok_01_a9f2x',
    customerName: 'Diner T1',
    status: 'cooking',
    items: [
      { id: 'oi-1', menuItemId: 'item-1', name: 'Truffle Tagliatelle', price: 26.50, quantity: 1, notes: 'Extra Parmigiano' },
      { id: 'oi-2', menuItemId: 'item-7', name: 'Smoked Yuzu Dragon Cocktail', price: 15.00, quantity: 2 },
    ],
    totalAmount: 56.50,
    paymentStatus: 'unpaid',
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    estimatedPrepTime: 14,
    priority: 'normal',
  },
  {
    id: 'ord-102',
    tableNumber: 2,
    tableToken: 'tbl_tok_02_b8k1y',
    customerName: 'Diner T2',
    status: 'pending',
    items: [
      { id: 'oi-3', menuItemId: 'item-2', name: 'Smoked Wagyu Burger', price: 22.00, quantity: 2, notes: 'Medium rare' },
      { id: 'oi-4', menuItemId: 'item-4', name: 'Artisan Burrata & Heirloom Salad', price: 16.50, quantity: 1 },
      { id: 'oi-5', menuItemId: 'item-8', name: 'Matcha Espresso Fusion', price: 7.50, quantity: 2 },
    ],
    totalAmount: 75.50,
    paymentStatus: 'unpaid',
    createdAt: new Date(Date.now() - 4 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 60000).toISOString(),
    estimatedPrepTime: 12,
    priority: 'high',
  },
  {
    id: 'ord-103',
    tableNumber: 4,
    tableToken: 'tbl_tok_04_d6p4w',
    customerName: 'Diner T4',
    status: 'ready',
    items: [
      { id: 'oi-6', menuItemId: 'item-3', name: 'Pan-Seared Atlantic Salmon', price: 28.00, quantity: 2 },
      { id: 'oi-7', menuItemId: 'item-5', name: 'Charred Octopus Tapas', price: 18.00, quantity: 1 },
      { id: 'oi-8', menuItemId: 'item-6', name: 'Valrhona Chocolate Lava Cake', price: 12.50, quantity: 2 },
    ],
    totalAmount: 99.00,
    paymentStatus: 'unpaid',
    createdAt: new Date(Date.now() - 18 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60000).toISOString(),
    estimatedPrepTime: 16,
    priority: 'vip',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: 'inv-1', name: 'Fresh Atlantic Salmon Fillet', category: 'Seafood', quantity: 4.5, unit: 'kg', reorderLevel: 8.0, unitCost: 22.00, supplier: 'OceanFresh Seafood Co.', status: 'low' },
  { id: 'inv-2', name: 'Wagyu Beef Patties (180g)', category: 'Meat', quantity: 36, unit: 'pcs', reorderLevel: 20, unitCost: 4.50, supplier: 'Prime Cut Meats', status: 'ok' },
  { id: 'inv-3', name: 'Black Truffle Oil', category: 'Pantry', quantity: 1.2, unit: 'L', reorderLevel: 2.0, unitCost: 65.00, supplier: 'Truffle Artisans', status: 'low' },
  { id: 'inv-4', name: 'Heirloom Tomatoes', category: 'Produce', quantity: 15, unit: 'kg', reorderLevel: 5.0, unitCost: 3.20, supplier: 'Green Valley Organic', status: 'ok' },
  { id: 'inv-5', name: 'Puglia Burrata Cheese', category: 'Dairy', quantity: 24, unit: 'balls', reorderLevel: 10, unitCost: 3.80, supplier: 'Milano Dairy Import', status: 'ok' },
  { id: 'inv-6', name: 'Uji Ceremonial Matcha', category: 'Beverage', quantity: 0.8, unit: 'kg', reorderLevel: 0.5, unitCost: 80.00, supplier: 'Kyoto Tea Importers', status: 'ok' },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-101',
    timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
    userId: 'user-customer-01',
    userRole: 'customer',
    userName: 'Guest @ Table 4',
    action: 'CREATE_ORDER',
    resource: 'Order #ord-103',
    ipAddress: '192.168.1.104',
    status: 'success',
    details: 'Placed order via QR scan at Table 4. Server verified Zod schema & recalculated total.',
  },
  {
    id: 'log-102',
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    userId: 'user-kitchen-01',
    userRole: 'kitchen',
    userName: 'Chef Marco',
    action: 'UPDATE_ORDER_STATUS',
    resource: 'Order #ord-101 -> COOKING',
    ipAddress: '192.168.1.20',
    status: 'success',
    details: 'Kitchen station updated prep state. RLS rule verified kitchen role privileges.',
  },
  {
    id: 'log-103',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    userId: 'user-staff-01',
    userRole: 'staff',
    userName: 'Sarah J.',
    action: 'WAITER_CALL_ACKNOWLEDGED',
    resource: 'Table #2',
    ipAddress: '192.168.1.33',
    status: 'success',
    details: 'Floor staff cleared waiter assistance alert.',
  },
  {
    id: 'log-104',
    timestamp: new Date(Date.now() - 22 * 60000).toISOString(),
    userId: 'unauthorized-anon',
    userRole: 'customer',
    userName: 'Anonymous IP',
    action: 'MUTATE_INVENTORY_ATTEMPT',
    resource: 'inventory_items',
    ipAddress: '203.0.113.42',
    status: 'blocked',
    details: 'BLOCKED BY SUPABASE RLS: Customer role attempted restricted UPDATE on inventory_items table.',
  },
];

export const INITIAL_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ins-1',
    title: 'Dynamic Pricing Opportunity',
    type: 'pricing',
    description: 'Truffle Tagliatelle velocity spiked +40% during peak hour (7:30-8:30 PM). High margin elasticity detected.',
    recommendation: 'Increase dinner price by +$2.50 or introduce a Chef Signature Truffle & Wine pairing set.',
    impact: 'High (+12% Revenue)',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 'ins-2',
    title: 'Inventory Stockout Risk Alert',
    type: 'inventory',
    description: 'Atlantic Salmon stock is down to 4.5kg (approx. 5 servings remaining). Demand projection exceeds current stock.',
    recommendation: 'Trigger instant automated replenishment alert or feature Charred Octopus special on QR menu top banner.',
    impact: 'Critical (Stockout Prevention)',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: 'ins-3',
    title: 'Kitchen Bottleneck & Prep Latency',
    type: 'efficiency',
    description: 'Order #ord-102 pending prep time elevated to 14 mins due to high concurrent appetizer orders.',
    recommendation: 'Prioritize cold starter assembly station to reduce customer wait time by 4.5 minutes.',
    impact: 'Medium (-25% Wait Time)',
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
  },
];
